name: Continuous Deployment
on:
  push:
    tags:
    - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Publish for 5.0
      run: dotnet publish -o dist/5.0 -f net5.0 -c Release src/EFMigrate.sln
    - name: Publish for 3.1
      run: dotnet publish -o dist/3.1 -f netcoreapp3.1 -c Release src/EFMigrate.sln
    - name: Upload artifacts for 5.0
      uses: actions/upload-artifact@v2
      with:
        name: '5.0'
        path: dist/5.0
    - name: Upload artifacts for 3.1
      uses: actions/upload-artifact@v2
      with:
        name: '3.1'
        path: dist/3.1
    - name: Upload Dockerfile
      uses: actions/upload-artifact@v2
      with:
        name: docker
        path: src/EFMigrate/Dockerfile
  publish:
    name: Publish
    runs-on: ubuntu-18.04
    needs: build
    steps:
    - name: Download artifacts for 5.0
      uses: actions/download-artifact@v2
      with:
        name: '5.0'
        path: '5.0'
    - name: Download artifacts for 3.1
      uses: actions/download-artifact@v2
      with:
        name: '3.1'
        path: '3.1'
    - name: Download Dockerfile
      uses: actions/download-artifact@v2
      with:
        name: docker
    - name: Build image for 5.0
      run: docker build -t ultimaweapon/ef-migrate:${GITHUB_REF##*/} --build-arg FRAMEWORK=5.0 -f Dockerfile 5.0
      if: ${{ startsWith(github.ref, 'refs/tags/5') }}
    - name: Build image for 3.1
      run: docker build -t ultimaweapon/ef-migrate:${GITHUB_REF##*/} --build-arg FRAMEWORK=3.1 -f Dockerfile 3.1
      if: ${{ startsWith(github.ref, 'refs/tags/3') }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ultimaweapon
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push image for 5.0
      run: docker push ultimaweapon/ef-migrate:${GITHUB_REF##*/}
      if: ${{ startsWith(github.ref, 'refs/tags/5') }}
    - name: Push image for 3.1
      run: docker push ultimaweapon/ef-migrate:${GITHUB_REF##*/}
      if: ${{ startsWith(github.ref, 'refs/tags/3') }}
