name: Continuous Integration
on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build
      run: dotnet build src/EFMigrate.sln
